services:
  - type: web
    name: whiteboard-server
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
    pullRequestPreviewsEnabled: false
