services:
  - type: web
    name: whiteboard-server
    env: docker
    plan: free
    region: oregon
    dockerfilePath: server/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    healthCheckPath: /health
